# Generated by Django 5.0.3 on 2024-03-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('ts_init', models.IntegerField(null=True)),
                ('ts_end', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Lap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.IntegerField(null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pwa.workout')),
            ],
        ),
    ]
